# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1irhk9XO3RAkQGPQwKrzdrMNw2tO--TNS
"""



import os
from pptx import Presentation

current_dir='/home/sahil/Desktop/text_summarize'
#os.path.dirname(os.path.realpath(/content/drive/My Drive/hack/test.pptx))

prs = Presentation(current_dir+'/template_sample.pptx')
title_slide_layout = prs.slide_layouts[1]
slide = prs.slides.add_slide(title_slide_layout)
title = slide.shapes.title
subtitle = slide.placeholders[1]

title.text = "Test Summarized"
subtitle.text = "hello everyone!!"

prs.save('/home/sahil/Desktop/text_summarize/test.pptx')



